# my global config
global:
  scrape_interval: 20s # Set the scrape interval to every 20 seconds. Default is every 1 minute.
  evaluation_interval: 20s # Evaluate rules every 20 seconds. The default isevery 1 minute.
# scrape_timeout is set to the global default (10s).
# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
# The job name is added as a label `job=<job_name>` to any timeseriesn scraped from this config.
  - job_name: "prometheus"
    metrics_path: '/metrics'
    scheme: 'https'
    scrape_interval: 10s # override default value
    scrape_timeout: 10s # override default value
    static_configs:
      - targets: ['cuddly-space-funicular-6r655g594xwc4g7j-9090.app.github.dev'] # The target here it's Prometheus itself.